name: Run IITI Scraper Every 7 Days

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:     # Manual trigger option

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip Install beautifulsoup4 requests PyPDF2 pandas tqdm pathway

    - name: Run the scraper
      run: python data/scraper.py

    - name: Run the cleaner
      run: python data/data_cleaner.py
